_wandb:
    value:
        cli_version: 0.24.2
        e:
            oubtrnj4o9t3rgeyfelto6v9vclcy1lc:
                codePath: training\ollama_automation.py
                codePathLocal: training\ollama_automation.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "524286947328"
                        used: "321185656832"
                email: yashashmathur2005@gmail.com
                executable: C:\Python313\python.exe
                git:
                    commit: f56e1db1bd064e706ca8809ca3c5f36b5b8213ce
                    remote: https://github.com/mathuryashash/AEGIS-ENV.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-4357e04b-4975-64c5-27e8-ccb234ae9cf4
                host: Yashashs-laptop
                memory:
                    total: "16869285888"
                os: Windows-11-10.0.26200-SP0
                program: D:\hackathon round 2 meta\training\ollama_automation.py
                python: CPython 3.13.3
                root: D:\hackathon round 2 meta
                startedAt: "2026-04-25T10:09:24.298526Z"
                writerId: oubtrnj4o9t3rgeyfelto6v9vclcy1lc
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 49
                - 105
            "2":
                - 49
                - 105
            "3":
                - 13
            "4": 3.13.3
            "5": 0.24.2
            "8":
                - 2
                - 3
            "12": 0.24.2
            "13": windows-amd64
